In [2]:
import numpy as np

In [3]:
b = np.array([[1,2,3], [6,7,8]])

In [4]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [5]:
b[:,1]=100

In [6]:
b

array([[  1, 100,   3],
       [  6, 100,   8]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [14]:
np.random.rand(3,3)

array([[0.93901701, 0.3253807 , 0.19624116],
       [0.28781455, 0.91374312, 0.94882128],
       [0.87804225, 0.15246671, 0.42242389]])

In [15]:
np.random.randint(5,10,size=(3,3))

array([[5, 6, 8],
       [6, 6, 8],
       [5, 9, 5]])

In [16]:
b.shape

(2, 3)

In [17]:
a = np.random.randint(1,10,size=(5,5))

In [18]:
a


array([[2, 7, 3, 3, 6],
       [9, 1, 2, 6, 5],
       [5, 8, 7, 4, 4],
       [4, 1, 8, 5, 9],
       [2, 5, 7, 8, 4]])

In [19]:
a.shape

(5, 5)

In [20]:
a = a.reshape(10,10) #olabilecek bir shape yazmak lazim

ValueError: cannot reshape array of size 25 into shape (10,10)

In [21]:
a = a.reshape(-1)

In [22]:
a


array([2, 7, 3, 3, 6, 9, 1, 2, 6, 5, 5, 8, 7, 4, 4, 4, 1, 8, 5, 9, 2, 5,
       7, 8, 4])

In [23]:
a = a.ravel()

In [24]:
a


array([2, 7, 3, 3, 6, 9, 1, 2, 6, 5, 5, 8, 7, 4, 4, 4, 1, 8, 5, 9, 2, 5,
       7, 8, 4])

In [25]:
my_con = np.random.randint(1,10,size=(5,4))

In [26]:
my_con

array([[7, 4, 8, 2],
       [8, 3, 9, 4],
       [7, 7, 8, 6],
       [9, 2, 5, 3],
       [6, 2, 6, 1]])

In [27]:
my_con[1,[2,3]]

array([9, 4])

In [28]:
my_con[[3,2],2]

array([5, 8])

In [29]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
b

array([[5, 6],
       [7, 8]])

In [32]:
x = np.stack((a,b))

In [33]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
x.ndim

3

In [35]:
x.shape

(2, 2, 2)

In [36]:
y = np.hstack((a,b)) # yataya cevirmek icin #Horizantal stack

In [37]:
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
y = np.vstack((a,b)) # dikeye cevirmek icin  #Vertical stack

In [39]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
bigger_than_5= array_1>5
bigger_than_5                     #arrayde 1 den buyukleri gosterir

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
array_1[bigger_than_5]   #sadece 5 den buyuklerini alir# buna filterin deniyor
#bunu cok kullanacagiz

array([ 6,  7,  8,  9, 10, 11, 12])

In [43]:
array_1[array_1>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
array_1[ (array_1 >2) & (array_1 <5) ]

array([3, 4])

In [50]:
np.log(x)

array([[[0.        , 0.69314718],
        [1.09861229, 1.38629436]],

       [[1.60943791, 1.79175947],
        [1.94591015, 2.07944154]]])

In [51]:
np.exp(x)

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [53]:
np.power(x,2)  #x in karesini alir

array([[[ 1,  4],
        [ 9, 16]],

       [[25, 36],
        [49, 64]]], dtype=int32)

In [54]:
np.power(x,3)

array([[[  1,   8],
        [ 27,  64]],

       [[125, 216],
        [343, 512]]], dtype=int32)

In [55]:
import pandas as pd

In [56]:
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [58]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [59]:
pd.Series(labels)

0    X
1    y
2    z
3    h
dtype: object

In [60]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int32

In [61]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [62]:
pd.Series(my_list,index=labels)

X     5
y    10
z    15
h    20
dtype: int64

In [63]:
ser = pd.Series([5,10,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])

In [64]:
ser

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [68]:
ser.sort_values()

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [67]:
ser.sort_index()

France     15
Germany    10
Greece     30
Turkey     25
UK         20
USA         5
dtype: int64

In [69]:
"Turkey" in ser

True

In [70]:
"Holland" in ser

False

In [71]:
"Turkey " in ser

False

In [72]:
ser.isin([55])

USA        False
Germany    False
France     False
UK         False
Turkey     False
Greece     False
dtype: bool

In [73]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [74]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [75]:
ser.items

<bound method Series.items of USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64>

In [76]:
for key,value in ser.items():
    print(key,value)

USA 5
Germany 10
France 15
UK 20
Turkey 25
Greece 30


In [77]:
m= np.arange(1,30,2).reshape((3,5))
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [79]:
df = pd.DataFrame(m,columns=["col1","col2","col3","col4","col5"])
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [80]:
df.head(1)

col1  col2  col3  col4  col5
0     1     3     5     7     9

In [81]:
df.head(0)

Empty DataFrame
Columns: [col1, col2, col3, col4, col5]
Index: []

In [83]:
df.sample(2) #random deger getirir

col1  col2  col3  col4  col5
2    21    23    25    27    29
1    11    13    15    17    19

In [84]:
df.tail(1)

col1  col2  col3  col4  col5
2    21    23    25    27    29